baseURL = 'https://cheip.dev/'
languageCode = 'en-us'
title = 'Simone Capodicasa'

[module]
[[module.imports]]
    path = 'graysx'

theme = 'graysx'

[params]

    # Socials
    twitter = "#"
    facebook = "https://www.facebook.com/homechief/"
    github = "#"
    instagram = "https://www.instagram.com/cheip/"
